package:
  name: anki_utilities
  version: "0.0.007"

source:
  path: ../anki_utilities

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - pypdf2
    - pillow

about:
  home: https://github.com/suri5471/anki_utilities
  license: MIT
  license_file: LICENSE
  summary: Convert pdf to flashcard deck.
