"""Convert pdf files into lists of images."""

import PyPDF2
from PIL import Image


def extract_page_images(pdf_path):
	"""Extract the each image from a pdf file.

	This only works for pdf files where each page is a separate image file,
	as for example in scanned files or files generated by lecture notes.
	"""
    image_list = []
    data_list = []
    with open(pdf_path, 'rb') as file:
        pdf = PyPDF2.PdfFileReader(file)
        for p in range(pdf.getNumPages()):   
            page = pdf.getPage(p)
            xObject = page['/Resources']['/XObject'].getObject()
            
            for obj in xObject:
            
                if xObject[obj]['/Subtype'] == '/Image':
                    size = (xObject[obj]['/Width'], xObject[obj]['/Height'])
                    data = xObject[obj].getData()
                    if xObject[obj]['/ColorSpace'] == '/DeviceRGB':
                        mode = "RGB"
                    else:
                        mode = "P"

                    if xObject[obj]['/Filter'] == '/FlateDecode':
                        img = Image.frombytes(mode, size, data)
                        image_list.append(img)
                    elif xObject[obj]['/Filter'] == '/DCTDecode':
                        img = open(obj[1:] + '.jpg', 'wb')
                        img.write(data)
                        img.close()
                    elif xObject[obj]['/Filter'] == '/JPXDecode':
                        img = open(obj[1:] + '.jp2', 'wb')
                        img.write(data)
                        img.close()
    return image_list